export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// login/logout buttons, user account and avatar
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header></header>
        <main>
        {children}
        </main>
      </body>
    </html>
  )
}
