import StyledComponentsRegistry from "./_styles/registy";
import "@/app/_styles/globals.css"
import Header from "@/Components/Headers/Header";
import QuickAccess from "@/Components/Headers/QuickAccess";
import { AppLayout } from "@/Components/Layouts/AppLayouts";
import { IBM_Plex_Sans_Arabic, Noto_Naskh_Arabic } from "next/font/google"
import { Toaster } from "react-hot-toast";


export const IBM = IBM_Plex_Sans_Arabic({
  variable: "--font-heading",
  subsets: ["arabic"],
  style: "normal",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap"
});

export const Noto = Noto_Naskh_Arabic({
  variable: "--font-paragraph",
  subsets: ["arabic"],
  style: "normal",
  weight: ["400", "500", "600", "700"],
  display: "swap"
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// login/logout buttons, user account and avatar
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body>
           {/* TODO:  the animated layout is going to be here inside the body*/}
          <Header>
            <QuickAccess/>
          </Header>
          <AppLayout>
            <Toaster position="top-right"/>
            { children }
          </AppLayout>
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}

 
